services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://user:password@localhost:5432/database
    ports:
      - "3000:3000"
