import { expect, test } from "vitest";

import { checkLintDirectives } from "./check-lint-directives.ts";

test("keeps only reviewable next-line exceptions and ignores strings", () => {
  const source = [
    "// eslint-disable-next-line no-debugger -- Required boundary.",
    "// eslint-disable-next-line @typescript-eslint/no-explicit-any, no-debugger -- Required boundary.",
    "// react-doctor-disable-next-line react-doctor/no-effect -- Required boundary.",
    'const text = "/* eslint-disable */";',
    "const template = `// oxlint-disable-next-line no-debugger`;",
    "/* eslint-disable no-debugger */",
    "// eslint-disable no-debugger",
    "// eslint-disable-line no-debugger -- Reason.",
    "/* eslint-disable-next-line no-debugger -- Reason. */",
    "/* eslint-enable no-debugger */",
    "/* eslint no-debugger: 0 */",
    "/* eslint\n no-debugger: 0\n */",
    "/* global supplied */",
    "/* globals supplied */",
    "/* eslint-env node */",
    "/* exported supplied */",
    "// oxlint-disable no-debugger",
    "// oxlint-disable-line no-debugger",
    "// oxlint-disable-next-line no-debugger -- Reason.",
    "// oxlint-enable no-debugger",
    "/* oxlint-disable no-debugger */",
    "// react-doctor-disable no-effect",
    "// react-doctor-disable-line no-effect",
    "/* react-doctor-disable-next-line no-effect -- Reason. */",
    "// eslint-disable-next-line no-debugger",
    "// eslint-disable-next-line no-debugger --   ",
    "// eslint-disable-next-line -- Reason.",
    "// react-doctor-disable-next-line no-effect",
    "// react-doctor-disable-next-line -- Reason.",
    "// oxlint-disable-file no-debugger",
    "// react-doctor-disable-file no-effect",
    "// eslint-disable-next-line no-debugger -- Reason.",
    "/* eslint no-debugger: 0 */",
    "// eslint-disable-next-line -- -- Reason.",
    "// note // react-doctor-disable-line react-doctor/no-array-index-as-key",
    "/* note react-doctor-disable-next-line x -- r */",
    "// eslint-disable-next-line no-debugger -- note // react-doctor-disable-line react-doctor/no-array-index-as-key",
    'const doctorText = "// note // react-doctor-disable-line react-doctor/no-array-index-as-key";',
  ].join("\n");

  expect(
    checkLintDirectives(source, "directives.ts").map(({ line }) => ({ line })),
  ).toEqual([
    { line: 3 },
    { line: 6 },
    { line: 7 },
    { line: 8 },
    { line: 9 },
    { line: 10 },
    { line: 11 },
    { line: 12 },
    { line: 15 },
    { line: 16 },
    { line: 17 },
    { line: 18 },
    { line: 19 },
    { line: 20 },
    { line: 21 },
    { line: 22 },
    { line: 23 },
    { line: 24 },
    { line: 25 },
    { line: 26 },
    { line: 27 },
    { line: 28 },
    { line: 29 },
    { line: 30 },
    { line: 31 },
    { line: 32 },
    { line: 33 },
    { line: 35 },
    { line: 36 },
    { line: 37 },
    { line: 38 },
    { line: 39 },
  ]);
});
