/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WizardRouteImport } from './routes/_wizard'
import { Route as WizardIndexRouteImport } from './routes/_wizard.index'
import { Route as WizardOutcomeRouteImport } from './routes/_wizard.outcome'
import { Route as WizardResultRouteImport } from './routes/_wizard.result'
import { Route as WizardReviewRouteImport } from './routes/_wizard.review'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc.$'

const WizardRoute = WizardRouteImport.update({
  id: '/_wizard',
  getParentRoute: () => rootRouteImport,
} as any)
const WizardIndexRoute = WizardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WizardRoute,
} as any)
const WizardOutcomeRoute = WizardOutcomeRouteImport.update({
  id: '/outcome',
  path: '/outcome',
  getParentRoute: () => WizardRoute,
} as any)
const WizardResultRoute = WizardResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => WizardRoute,
} as any)
const WizardReviewRoute = WizardReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => WizardRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof WizardIndexRoute
  '/outcome': typeof WizardOutcomeRoute
  '/result': typeof WizardResultRoute
  '/review': typeof WizardReviewRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesByTo {
  '/outcome': typeof WizardOutcomeRoute
  '/result': typeof WizardResultRoute
  '/review': typeof WizardReviewRoute
  '/': typeof WizardIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_wizard': typeof WizardRouteWithChildren
  '/_wizard/outcome': typeof WizardOutcomeRoute
  '/_wizard/result': typeof WizardResultRoute
  '/_wizard/review': typeof WizardReviewRoute
  '/_wizard/': typeof WizardIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/outcome' | '/result' | '/review' | '/api/trpc/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/outcome' | '/result' | '/review' | '/' | '/api/trpc/$'
  id:
    | '__root__'
    | '/_wizard'
    | '/_wizard/outcome'
    | '/_wizard/result'
    | '/_wizard/review'
    | '/_wizard/'
    | '/api/trpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  WizardRoute: typeof WizardRouteWithChildren
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_wizard': {
      id: '/_wizard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WizardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_wizard/': {
      id: '/_wizard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WizardIndexRouteImport
      parentRoute: typeof WizardRoute
    }
    '/_wizard/outcome': {
      id: '/_wizard/outcome'
      path: '/outcome'
      fullPath: '/outcome'
      preLoaderRoute: typeof WizardOutcomeRouteImport
      parentRoute: typeof WizardRoute
    }
    '/_wizard/result': {
      id: '/_wizard/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof WizardResultRouteImport
      parentRoute: typeof WizardRoute
    }
    '/_wizard/review': {
      id: '/_wizard/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof WizardReviewRouteImport
      parentRoute: typeof WizardRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface WizardRouteChildren {
  WizardOutcomeRoute: typeof WizardOutcomeRoute
  WizardResultRoute: typeof WizardResultRoute
  WizardReviewRoute: typeof WizardReviewRoute
  WizardIndexRoute: typeof WizardIndexRoute
}

const WizardRouteChildren: WizardRouteChildren = {
  WizardOutcomeRoute: WizardOutcomeRoute,
  WizardResultRoute: WizardResultRoute,
  WizardReviewRoute: WizardReviewRoute,
  WizardIndexRoute: WizardIndexRoute,
}

const WizardRouteWithChildren =
  WizardRoute._addFileChildren(WizardRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  WizardRoute: WizardRouteWithChildren,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
