name: Backend Quality Checks

on:
  pull_request:
    paths:
      - .github/actions/backend/**
      - .github/workflows/backend-checks.yaml
      - backend/**

  push:
    branches:
      - main
    paths:
      - .github/actions/backend/**
      - .github/workflows/backend-checks.yaml
      - backend/**

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  quality-checks:
    name: Lint, vet and test the backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: "Setup Go and Task"
        uses: ./.github/actions/backend/setup-env

      - name: "Run linting, formatting and tests"
        uses: ./.github/actions/backend/quality-checks
