name: Backend Quality Checks

on:
  pull_request:
    paths:
      - .github/actions/backend/**
      - .github/workflows/backend-checks.yaml
      - backend/**

  push:
    branches:
      - main
    paths:
      - .github/actions/backend/**
      - .github/workflows/backend-checks.yaml
      - backend/**

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  quality-checks:
    name: Lint, vet and test the backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: "Setup Go and Task"
        uses: ./.github/actions/backend/setup-env

      - name: "Run linting, formatting and tests"
        uses: ./.github/actions/backend/quality-checks
