name: Frontend Quality Checks

on:
  pull_request:
    paths:
      - .github/actions/frontend/**
      - .github/workflows/frontend-checks.yaml
      - frontend/**

  push:
    branches:
      - main
    paths:
      - .github/actions/frontend/**
      - .github/workflows/frontend-checks.yaml
      - frontend/**

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  quality-checks:
    name: Run code quality checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: "Setup Node.js, pnpm and dependencies"
        uses: ./.github/actions/frontend/setup-env

      - name: "Run linting, formatting and type checks"
        uses: ./.github/actions/frontend/quality-checks
