name: Repository Checks

on:
  pull_request:

  push:
    branches:
      - main

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  secret-scan:
    name: Scan the repository for secrets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Check secrets
        uses: docker://secretlint/secretlint:v13.0.7@sha256:4e0d997d1c395992de2cce32442fd5ff8ad4f3460a765b681c02c38226476cb4
        with:
          args: secretlint --maskSecrets --no-gitignore **/*
